apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage_vault
  annotations:
    vault.io/secrets-path: secrets/kv/backstage
    #vault.io/secrets-engine: kv
spec:
 type: service
 owner: Eswar
 lifecycle: experimental
