apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-test-api
  description: A sample API for testing
  tags:
    - sample
spec:
  type: openapi
  lifecycle: experimental
  owner: user:eswarr07
  definition:
    $text: ./openapi.yaml
